/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h> 
/* Header for class com_nqy_mycode_jni_Person */

#ifndef _Included_com_nqy_mycode_jni_Person
#define _Included_com_nqy_mycode_jni_Person
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nqy_mycode_jni_Person
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_nqy_mycode_jni_Person_getName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
